{{- if .Values.clickhouse.existingSecret -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-ingestor.fullname" . }}-clickhouse
  labels:
    {{- include "k8s-ingestor.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "ClickHouse password is required" .Values.clickhouse.password }}
{{- end }}
